"""Tests for per-repo Nix toolchains (turnstone/core/nixenv.py).

Detection, flake rendering and command wrapping are pure functions of the
filesystem, so they're tested directly. Actually building a shell needs Nix and
a network, so that path is exercised in the container rather than here.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from turnstone.core import nixenv


@pytest.fixture(autouse=True)
def _workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("TURNSTONE_WORKSPACE", str(tmp_path / "workspace"))


class TestDetect:
    def test_go_repo(self, tmp_path: Path) -> None:
        (tmp_path / "go.mod").write_text("module x\n")
        spec = nixenv.detect(tmp_path)
        assert "go" in spec.packages and spec.markers == ["go.mod"]

    def test_polyglot_repo_gets_both(self, tmp_path: Path) -> None:
        # Kokoro-go is real: go.mod AND pyproject.toml in one tree.
        (tmp_path / "go.mod").write_text("module x\n")
        (tmp_path / "pyproject.toml").write_text("[project]\n")
        spec = nixenv.detect(tmp_path)
        assert "go" in spec.packages and "python312" in spec.packages
        assert set(spec.markers) == {"go.mod", "pyproject.toml"}

    def test_bare_repo_still_gets_an_interpreter(self, tmp_path: Path) -> None:
        # bobthesumo has no markers at all; that's the common case, not an edge.
        spec = nixenv.detect(tmp_path)
        assert spec.packages == ["python312"]
        assert spec.markers == []

    def test_repo_flake_wins_outright(self, tmp_path: Path) -> None:
        (tmp_path / "flake.nix").write_text("{}\n")
        (tmp_path / "go.mod").write_text("module x\n")
        spec = nixenv.detect(tmp_path)
        # The author's own declaration beats anything inferred.
        assert spec.repo_flake is True
        assert spec.packages == []

    def test_no_duplicate_packages(self, tmp_path: Path) -> None:
        (tmp_path / "pyproject.toml").write_text("[project]\n")
        (tmp_path / "requirements.txt").write_text("x\n")
        spec = nixenv.detect(tmp_path)
        assert spec.packages.count("python312") == 1


class TestRenderFlake:
    def test_includes_packages_and_is_marked(self) -> None:
        out = nixenv.render_flake(["go", "python312"])
        assert "pkgs.go" in out and "pkgs.python312" in out
        # The marker is load-bearing: provision only overwrites its own flake,
        # never one an agent or human has tuned.
        assert "Generated by turnstone" in out
        assert "devShells" in out and "mkShell" in out


class TestWrapCommand:
    def test_wraps_with_path_ref(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(nixenv, "nix_binary", lambda: "/usr/bin/nix")
        argv = ["opencode", "run", "--format", "json", "do; rm -rf /"]
        out = nixenv.wrap_command(argv, "/workspace/envs/ws1")
        assert out[:4] == ["/usr/bin/nix", "develop", "path:/workspace/envs/ws1", "--command"]
        # argv stays a vector, so shell metacharacters in a prompt are inert.
        assert out[4:] == argv
        assert out[-1] == "do; rm -rf /"

    def test_passthrough_without_nix(self, monkeypatch: pytest.MonkeyPatch) -> None:
        monkeypatch.setattr(nixenv, "nix_binary", lambda: None)
        argv = ["claude", "-p", "go"]
        assert nixenv.wrap_command(argv, "/env") == argv


class TestEnvDir:
    def test_env_dir_under_workspace(self) -> None:
        root = nixenv.workspace_root().resolve()
        assert str(nixenv.env_dir_for("ws1").resolve()).startswith(str(root))

    @pytest.mark.parametrize("bad", ["../escape", "a/b", "", "."])
    def test_rejects_unsafe_ws_id(self, bad: str) -> None:
        with pytest.raises(nixenv.NixEnvError):
            nixenv.env_dir_for(bad)

    def test_teardown(self) -> None:
        d = nixenv.env_dir_for("ws1")
        d.mkdir(parents=True)
        (d / "flake.nix").write_text("{}")
        assert nixenv.teardown("ws1") is True
        assert nixenv.teardown("ws1") is False
