"""Named, shareable Nix environments — a curated playground for dispatched agents.

A dispatched agent is only as useful as its ability to *verify* its own work,
and that needs the repo's toolchain.  Baking every runtime into the node image
doesn't scale: each repo would pay for every other repo's dependencies.

Nix solves this **in-process** — ``nix develop --command`` materializes a
toolchain into the container the agent already runs in.  No Docker socket, no
docker-in-docker, no sibling container, which is what makes this a tool call
rather than an architecture change.

Environments are **named and shared**, not per-workstream throwaways::

    /workspace/envs/            <- a git repository
        go-dev/flake.nix
        python-ml/flake.nix
        kokoro-go/flake.nix

Three things follow from that shape:

* **Curation.** Hit a missing library once, add it once, and every later
  dispatch has it.  That is the difference between an environment and a guess.
* **Reuse.** Ten repos on the same stack share one warm store and one eval.
* **Portability.** The directory is a git repo of plain flakes, so it can be
  committed, pushed, and cloned onto another machine where ``nix develop``
  reproduces it *without turnstone in the picture at all*.

Generated flakes are multi-system (``forAllSystems``): an environment that only
builds on x86 isn't portable, and one of the repos this was written for is a
Raspberry Pi project.

Nix evaluates the small env directory rather than the worktree.  A flake
reference copies its directory into the store and redoes that whenever the
contents change: measured on a 2 MB repo, evaluating from the worktree cost
**16.9s per command** after each agent edit versus **0.27s** from the env dir.
The agent edits constantly, so that gap is the whole design.

``path:`` references are used rather than plain paths because a flake inside a
git repo is evaluated from the *git tree*; a file that was never committed is
invisible to it (Nix fails and suggests ``git add -N``).  ``path:`` reads the
filesystem directly.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from turnstone.core.log import get_logger
from turnstone.core.workspace import workspace_root

log = get_logger(__name__)

_NIX_CANDIDATES = (
    "/nix/var/nix/profiles/default/bin/nix",
    "/run/current-system/sw/bin/nix",
)

# Environment names are operator-facing and become directory names.
_SAFE_NAME = re.compile(r"^[a-z0-9][a-z0-9._-]{0,63}$")
# nixpkgs attribute names, validated before they reach a generated flake.
_SAFE_PKG = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")

TOOLCHAIN_MARKERS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("go.mod", ("go", "gopls")),
    ("Cargo.toml", ("cargo", "rustc")),
    ("pyproject.toml", ("python312", "uv")),
    ("requirements.txt", ("python312", "uv")),
    ("setup.py", ("python312",)),
    ("package.json", ("nodejs_22",)),
    ("pnpm-lock.yaml", ("nodejs_22", "pnpm")),
    ("Gemfile", ("ruby",)),
    ("pom.xml", ("maven", "jdk")),
    ("build.gradle", ("gradle", "jdk")),
    ("CMakeLists.txt", ("cmake", "gcc")),
    ("Makefile", ("gnumake",)),
)

# Extension-based fallback for repos with no build file, checked in order.
_EXTENSION_FALLBACK: tuple[tuple[str, tuple[str, ...]], ...] = (
    (".java", ("jdk", "maven")),
    (".go", ("go", "gopls")),
    (".rs", ("cargo", "rustc")),
    (".ts", ("nodejs_22",)),
    (".js", ("nodejs_22",)),
    (".c", ("gcc", "gnumake")),
    (".cpp", ("gcc", "cmake")),
    (".py", ("python312", "uv")),
)

_BASE_PACKAGES = ("git", "coreutils", "bash")
_PROVISION_TIMEOUT = 1800
_NIXPKGS_REF = "github:NixOS/nixpkgs/nixos-unstable"
_SYSTEMS = ("x86_64-linux", "aarch64-linux", "x86_64-darwin", "aarch64-darwin")

_GENERATED_MARKER = "Generated by turnstone"


class NixEnvError(RuntimeError):
    """Raised for bad names, missing Nix, or a shell that fails to build."""


@dataclass
class EnvSpec:
    packages: list[str] = field(default_factory=list)
    markers: list[str] = field(default_factory=list)
    repo_flake: bool = False


@dataclass
class Env:
    name: str
    path: Path
    packages: list[str]
    generated: bool = True


def nix_binary() -> str | None:
    for candidate in _NIX_CANDIDATES:
        if Path(candidate).is_file():
            return candidate
    return shutil.which("nix")


def is_available() -> bool:
    return nix_binary() is not None


def envs_root() -> Path:
    return workspace_root() / "envs"


def _validate_name(name: str) -> str:
    if not name or not _SAFE_NAME.match(name):
        raise NixEnvError(
            f"invalid environment name {name!r} "
            "(lowercase letters, digits, dot, dash, underscore)"
        )
    return name


def env_path(name: str) -> Path:
    return envs_root() / _validate_name(name)


def _git(*args: str, cwd: Path, timeout: int = 60) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # noqa: S603 - fixed binary, argv list
        ["git", *args], cwd=str(cwd), capture_output=True, text=True,
        errors="replace", timeout=timeout, check=False,
    )


def ensure_envs_repo() -> Path:
    """Make ``/workspace/envs`` a git repo so env changes are versioned.

    Version control is the portability story: the whole environment set can be
    pushed and cloned, and a bad edit is recoverable.
    """
    root = envs_root()
    root.mkdir(parents=True, exist_ok=True)
    if not (root / ".git").exists():
        _git("init", "-q", "-b", "main", cwd=root)
        _git("config", "user.email", "turnstone@localhost", cwd=root)
        _git("config", "user.name", "turnstone", cwd=root)
        (root / "README.md").write_text(
            "# turnstone agent environments\n\n"
            "Named Nix dev shells used by dispatched coding agents.\n"
            "Each directory holds a `flake.nix`; run `nix develop ./<name>` to\n"
            "enter one directly — turnstone is not required.\n",
            encoding="utf-8",
        )
        _commit(root, "init environment registry")
    return root


def _commit(root: Path, message: str) -> None:
    _git("add", "-A", cwd=root)
    result = _git("commit", "-q", "-m", message, cwd=root)
    if result.returncode != 0 and "nothing to commit" not in (result.stdout + result.stderr):
        log.debug("nixenv.commit_failed", detail=(result.stderr or result.stdout)[:200])


def detect(worktree: Path) -> EnvSpec:
    """Infer a toolchain from the files present in *worktree*.

    A repo's own ``flake.nix`` wins outright — the author's declaration beats
    anything inferred.  Otherwise every matching marker contributes, because
    polyglot repos are the normal case, not an edge one.
    """
    spec = EnvSpec()
    if (worktree / "flake.nix").is_file():
        spec.repo_flake = True
        spec.markers.append("flake.nix")
        return spec
    seen: set[str] = set()
    for marker, packages in TOOLCHAIN_MARKERS:
        if not (worktree / marker).exists():
            continue
        spec.markers.append(marker)
        for pkg in packages:
            if pkg not in seen:
                seen.add(pkg)
                spec.packages.append(pkg)
    if not spec.packages:
        # No build file at all. Fall back to source extensions before assuming
        # Python: a plain Java or Go project with no pom.xml/go.mod would
        # otherwise be handed an interpreter it can't use.
        for ext, packages in _EXTENSION_FALLBACK:
            if next(worktree.rglob(f"*{ext}"), None) is not None:
                spec.markers.append(f"*{ext}")
                spec.packages = list(packages)
                break
    if not spec.packages:
        spec.packages = ["python312"]
    return spec


def render_flake(packages: list[str]) -> str:
    """Generate a multi-system devShell flake.

    ``forAllSystems`` rather than a pinned system: an environment that only
    builds on x86 is not portable, and these are meant to be cloned onto other
    machines (including ARM).
    """
    for pkg in packages:
        if not _SAFE_PKG.match(pkg):
            raise NixEnvError(f"invalid package name: {pkg!r}")
    pkg_lines = "\n".join(f"            pkgs.{p}" for p in packages)
    systems = " ".join(f'"{s}"' for s in _SYSTEMS)
    return f"""{{
  # {_GENERATED_MARKER}. Edit freely — turnstone only overwrites flakes that
  # still carry this marker, so a hand-tuned environment is preserved.
  # Enter it directly with: nix develop ./<env-name>
  description = "turnstone agent environment";

  inputs.nixpkgs.url = "{_NIXPKGS_REF}";

  outputs = {{ self, nixpkgs }}:
    let
      systems = [ {systems} ];
      forAllSystems = f:
        nixpkgs.lib.genAttrs systems (system: f nixpkgs.legacyPackages.${{system}});
    in
    {{
      devShells = forAllSystems (pkgs: {{
        default = pkgs.mkShell {{
          packages = [
{pkg_lines}
          ];
        }};
      }});
    }};
}}
"""


def _packages_of(flake_text: str) -> list[str]:
    return re.findall(r"^\s*pkgs\.([A-Za-z0-9._-]+)\s*$", flake_text, re.MULTILINE)


def list_envs() -> list[Env]:
    """Every named environment in the registry."""
    root = envs_root()
    if not root.is_dir():
        return []
    out: list[Env] = []
    for path in sorted(root.iterdir()):
        flake = path / "flake.nix"
        if not path.is_dir() or path.name.startswith(".") or not flake.is_file():
            continue
        text = flake.read_text(encoding="utf-8", errors="replace")
        out.append(
            Env(
                name=path.name,
                path=path,
                packages=_packages_of(text),
                generated=_GENERATED_MARKER in text,
            )
        )
    return out


def get_env(name: str) -> Env | None:
    path = env_path(name)
    flake = path / "flake.nix"
    if not flake.is_file():
        return None
    text = flake.read_text(encoding="utf-8", errors="replace")
    return Env(
        name=name, path=path, packages=_packages_of(text), generated=_GENERATED_MARKER in text
    )


def create_env(name: str, packages: list[str], *, message: str = "") -> Env:
    """Create or replace a generated environment.

    A flake whose marker has been removed (hand-tuned) is never overwritten —
    curation has to survive an accidental re-provision.
    """
    root = ensure_envs_repo()
    path = env_path(name)
    path.mkdir(parents=True, exist_ok=True)
    flake = path / "flake.nix"
    if flake.is_file():
        existing = flake.read_text(encoding="utf-8", errors="replace")
        if _GENERATED_MARKER not in existing:
            raise NixEnvError(
                f"environment {name!r} was hand-edited; not overwriting it. "
                "Use action='add' to extend it, or delete it first."
            )
    merged = [*_BASE_PACKAGES, *[p for p in packages if p not in _BASE_PACKAGES]]
    flake.write_text(render_flake(merged), encoding="utf-8")
    _commit(root, message or f"env {name}: set packages")
    log.info("nixenv.env_created", name=name, packages=merged)
    return Env(name=name, path=path, packages=merged)


def add_packages(name: str, packages: list[str]) -> Env:
    """Extend an existing environment — the curation path."""
    env = get_env(name)
    if env is None:
        raise NixEnvError(f"no environment named {name!r}")
    if not env.generated:
        raise NixEnvError(
            f"environment {name!r} was hand-edited; add packages to its flake.nix directly."
        )
    for pkg in packages:
        if not _SAFE_PKG.match(pkg):
            raise NixEnvError(f"invalid package name: {pkg!r}")
    merged = list(env.packages) + [p for p in packages if p not in env.packages]
    root = ensure_envs_repo()
    (env.path / "flake.nix").write_text(render_flake(merged), encoding="utf-8")
    _commit(root, f"env {name}: add {', '.join(packages)}")
    return Env(name=name, path=env.path, packages=merged)


def env_for_repo(repo_name: str, worktree: Path) -> Env:
    """Bootstrap (or reuse) the named environment for a repo.

    Detection creates a *named* environment the operator can then curate, rather
    than an anonymous throwaway.
    """
    name = re.sub(r"[^a-z0-9._-]+", "-", repo_name.lower()).strip("-") or "default"
    existing = get_env(name)
    if existing is not None:
        return existing
    spec = detect(worktree)
    if spec.repo_flake:
        # The repo declares its own; use it in place rather than copying it out,
        # since it may reference sibling files.
        return Env(name=name, path=worktree, packages=[], generated=False)
    return create_env(name, spec.packages, message=f"env {name}: bootstrap from {repo_name}")


def provision(env: Env, *, timeout: int = _PROVISION_TIMEOUT) -> None:
    """Build the shell so the first dispatch doesn't pay the download."""
    nix = nix_binary()
    if nix is None:
        raise NixEnvError("nix is not installed on this node")
    try:
        proc = subprocess.run(  # noqa: S603 - fixed binary, argv list
            [nix, "develop", f"path:{env.path}", "--command", "true"],
            capture_output=True, text=True, errors="replace", timeout=timeout, check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise NixEnvError(f"nix develop timed out after {timeout}s") from exc
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or "").strip()
        raise NixEnvError(f"nix develop failed: {detail[-500:]}")
    log.info("nixenv.provisioned", name=env.name)


def wrap_command(argv: list[str], env_dir: str | Path) -> list[str]:
    """Wrap *argv* to run inside a provisioned shell.

    ``--command`` takes an argument vector, so a prompt containing quotes or
    ``;`` stays inert — the same discipline the rest of the dispatch path keeps.
    """
    nix = nix_binary()
    if nix is None:
        return argv
    return [nix, "develop", f"path:{env_dir}", "--command", *argv]


def delete_env(name: str) -> bool:
    path = env_path(name)
    if not path.exists():
        return False
    shutil.rmtree(path, ignore_errors=True)
    _commit(ensure_envs_repo(), f"env {name}: delete")
    return True
